### ISSUE TITLE
[Discussion] CalendarView 내 SelectedDate

### ISSUE THREAD

**Issue by ittzggd** [ittzggd/24HoursAreNotEnough#179]
**기존 로직 및 문제 사항**
- SelectedDate 가 @State로 선언되어있는 상황
- day가 아닌 Month 나 Year가 바뀌는 경우에 각각의 컴포넌트들에서 monthly 업데이트 메서드 호출
- datePicker로 selectedDate를 변경하는 경우 
    1. 날(day)만 변경되는 경우
      -  기존에 불러왔던 달별 기록이 class 내 dictionary에 존재하기 때문에 제대로된 데이터를 보여줌 
    2. 달, 년 이 변경되는 경우
      - 캘린더 상단 날짜 및 TagLog에서의 날짜는 picker 값에 따라 변경되는데, 해당 day, month 에 대한 totalAccTime 업데이트 안 됨 및 태그 로그 기록 없음으로 보여짐

**생각해본 로직**
- SelectedDate에서 Month, Year가 변경된 경우를 트리거로 monthly 업데이트 메서드 호출
- class 내부적으로 가지고 있는 값도 변경해주고, 메서드도 각각의 컴포넌트에서 따로 호출하지 않아도 됨
- 단 datePicker가 wheel 형태라 selectedDate의 잦은 변경으로 인한 잦은 메서드 호출을 방지하기 datePicker에서 사용되는 selection과 SelectedDate 분리

위의문제들을 발견해서 아래의 방식을 생각해보앗는데요 의견 부탁드립미다..총총...

**Comment by YunKi-H** [comment]
@State 가 아니라면 SelectedDate가 변경됨에 따라 뷰가 업데이트되지 않을텐데
@State 변수에는 get/set/didSet/willSet 같은 프로퍼티 옵저버를 적용 못해서 옛날에 포기했던거같긴 한데요
혹시 SelectedDate의 변경을 감지해서 로직을 호출하는 다른 방법이 있을까요

**Comment by YunKi-H** [comment]
onChange(of:perform:) 사용할 수 있네여
https://zeddios.tistory.com/1154

**Comment by ittzggd** [comment]
넹 가장 간단하게는 @state selectedDate가 있는 최상단에 onChange 를 달 수 있구여 아니면 Binding 자체를 extension하는 방법도 있습미다 사실 state 가 선언된 상단에서 값이 바뀌는 경우는 didSet이 동작하는데 Binding에서 변경된 경우에 didSet을 트리거 못시키는 거라서용

**Comment by YunKi-H** [comment]
https://www.hackingwithswift.com/quick-start/swiftui/how-to-run-some-code-when-state-changes-using-onchange
보고있는데 저는 onChange 다는쪽이 적합해보입니당
별로 안이뻐보이기는 한데 지금 코드보단 나을거같기도 하구여

datePicker에서 selection을 따로 분리하는건 어떤 로직으로 잦은 메서드 호출을 방지하게 되나여?

**Comment by ittzggd** [comment]
datePicker 자체가 휠 형태이다 보니까 왔다갔다 이동하면서(물론 날짜 선택 전까지는 selection이 변경되지 않지만) selectedDate의 변경이 잦을거라고 생각했습니다! selectedDate의 변경에 트리거를 건 상황에서  변경이 잦다는건 결국 api의 잦은 호출을 유도할 거라고 생각했습니당 이 부분을 picker를 보여주고 안보여주는 bool 값이 변경될때 selectedDate를 업데이트 해주면 조금 변경 횟수를 줄일 수 있지 않을까 싶었구여ㅕ

**Comment by YunKi-H** [comment]
사실 그건 지금도 picker 꺼질때 해당 달의 데이터를 받아오는 로직이라서
휠돌리는중엔 밑에 로그 표시가 안되더라도 picker 꺼지자마자 데이터가 갱신되고 선택된 날짜의 로그가 있다면 바로 표시될텐데여
아 지금 보고있던 로그를 보여주다가 갱신될때 같이 맞춰서 갱신시켜주자는 거였군여

**Comment by ittzggd** [comment]
네에 왜냐면 지금 로직상에서는 괜찮은데 제가 제시한 selectedDate가 변경되는 상황이 데이터를 받아오는 트리거가 된다면 기존 로직처럼 picker가 꺼질때 데이터를 받아오는 형태가 아니라 휠에서 날짜(월 혹은 년)를 바꿀 때 마다 받아오는 형태가 될테닉가용

**Comment by YunKi-H** [comment]
저는 좋아보입니당

**Comment by ittzggd** [comment]
고럼 말씀드린 방식으로 수정해도 될까요!
