### ISSUE TITLE
[Discussion] PullToRefresh now refreshed with today at HomeView

### ISSUE THREAD

**Issue by YunKi-H** [ittzggd/24HoursAreNotEnough#182]
**문제 사항**
- HomeView 에서 refresh 할때 Date() 기준으로 refresh함
- -> CalendarView에 표시되는 정보가 Date() 기준으로 갱신됨
- -> 이번달이 아닌 다른 달의 정보를 보고 있다가 HomeView로 이동해 새로고침을 하면 CalendarView에는 다른 달을 보고 있지만 이번달의 데이터가 대신 보이게 됨

**생각해본 해결방안**
1. selectedDate를 MainView로 끌어올려서 HomeView랑 CalendarView에 바인딩 시키기
2. selectedDate를 뷰모델에 집어넣고 각각 뷰에서 가져다 쓰기
3. HomeView에서 사용할 refresh와 CalendarView에서 사용할 refresh를 따로구현하기
4. 어디서 refresh하든 이번달의 정보로 갱신하는 대신 CalendarView에서 보고있던 달력도 이번달로 이동시키기

**Comment by ittzggd** [comment]
2번이 가장 나은 방안 같구여,, 생각해보니까 3번도 나쁘지 않겠다 싶긴 하네용.. 예시로 인스타그램 같은 경우도 홈 뷰에서 새로고침했을 때 탐색뷰에 영향을 주지는 않거든용 refresh가 따로 적용되는 방향인 것 같아서 고런 예시 생각하면 3번도 괜찮을 것 같읏ㅂ니다
